# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  database: d3vtde8gou86ph
  username: njdmkerghzbsji
  password: 7d56528d2eff20e07d38976e878f1bd7047678e6cee5b119e91898a95cdd0a80
  host: ec2-44-197-94-126.compute-1.amazonaws.com
  uri: postgres://njdmkerghzbsji:7d56528d2eff20e07d38976e878f1bd7047678e6cee5b119e91898a95cdd0a80@ec2-44-197-94-126.compute-1.amazonaws.com:5432/d3vtde8gou86ph
  heroku_cli: heroku pg:psql postgresql-globular-37926 --app bus-reservation-shriffle
  port: 5432

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
