# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  encoding: unicode
  adapter: postgresql
  database: bus_reservation
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: bus_reservation_development

test:
  <<: *default
  database: bus_reservation_test

production:
  <<: *default
  database: bus_reservation_production
